added ServoSpindle in the right place this time
OctoPrint/plugins.octoprint.org pull request #1004
Opened 2022-02-07 06:44 UTC by synman

2022-02-07 10:29 UTC, cp2004 commented
(Manually generated) preview: https://cp2004-plugins-octoprint-org-git-pr1004-cp2004.vercel.app/

2022-02-07 10:45 UTC, synman commented
thanks @cp2004 .  now I'm going to have to go back and clean up Better Grbl Support's page as this plugin's plugin page looks 1000 times nicer for some reason.

2022-02-23 22:45 UTC, synman commented
hey guys... @cp2004 whoever... seeing new plugins pop yet mine sits here in PR hell.  What's going on?

2022-02-23 23:00 UTC, cp2004 commented
I know jneilliii has been quite busy lately - the PSU control sub plugins are reviewed by kantlivelong, and they can be processed faster, other reviewers are requested when required. I just generate the previews and get involved when mentioned...

I've avoided doing plugin reviews particularly because I have plenty of other things to do - but I don't mind helping out @jneilliii if you want some help getting the pending reviews through.

2022-02-24 02:53 UTC, jneilliii commented
That would be great @cp2004 I've been slammed with work and probably wouldn't be able to get to them for a while anyway.

2022-02-24 03:15 UTC, synman commented
If you need help moving them thru review wise, I'm more than happy to pitch in.... this one aside as I'd have to recuse myself as a reviewer anyway.

2022-02-24 05:04 UTC, jneilliii requested changes
couple of minor points. don't really see any issues on the plugin side.

2022-02-24 05:04 UTC, jneilliii commented on _plugins/ServoSpindle.md
> +![grbl](https://user-images.githubusercontent.com/1299716/147993411-7005d1bb-53bf-4277-9e09-5022b40ccc0b.png)
prefer all images to be included in the PR in `/assets/img/plugins/ServoSpindle/`

2022-02-24 05:07 UTC, jneilliii commented on _plugins/ServoSpindle.md
> +archive: https://github.com/synman/OctoPrint-Servospindle/archive/master.zip
would probably be better to use main.zip instead of depend on GitHub's master branch redirect.

2022-02-24 05:08 UTC, jneilliii commented on _plugins/ServoSpindle.md
> +  python: ">=3,<4"
python compatibility mismatch between what you have here and what you have in your init.py file.

2022-02-24 05:47 UTC, synman commented on _plugins/ServoSpindle.md
> +featuredimage: /assets/img/plugins/bettergrblsupport/Grbl_logo.png
It's my own plugin

2022-02-24 05:52 UTC, synman commented on _plugins/ServoSpindle.md
> +archive: https://github.com/synman/OctoPrint-Servospindle/archive/master.zip
I'll fix this.   I am used to using master but I totally get it.  This repo is using the new naming conventions.

I generated this plugin using the bundled tools.  We should probably change it there as well.

2022-02-24 05:56 UTC, synman commented on _plugins/ServoSpindle.md
> +  python: ">=3,<4"
I have plans to bump the min python version to 3 just as soon as 1.8.0 comes out.

2022-02-24 12:24 UTC, cp2004 commented on _plugins/ServoSpindle.md
> +![grbl](https://user-images.githubusercontent.com/1299716/147993411-7005d1bb-53bf-4277-9e09-5022b40ccc0b.png)
Marked as resolved but nothing done, @synman?

2022-02-24 22:00 UTC, synman commented on _plugins/ServoSpindle.md
> +![grbl](https://user-images.githubusercontent.com/1299716/147993411-7005d1bb-53bf-4277-9e09-5022b40ccc0b.png)
Wait, what did I miss?  I copied over resources (the same links actually) that I have for the Grbl plugin.

2022-02-24 22:05 UTC, cp2004 commented on _plugins/ServoSpindle.md
> +![grbl](https://user-images.githubusercontent.com/1299716/147993411-7005d1bb-53bf-4277-9e09-5022b40ccc0b.png)
This is an image that is hosted externally from the plugin repository, it should be uploaded here rather than linked.

2022-02-26 18:15 UTC, synman commented on _plugins/ServoSpindle.md
> +![grbl](https://user-images.githubusercontent.com/1299716/147993411-7005d1bb-53bf-4277-9e09-5022b40ccc0b.png)
Ok, I'll address.  

Do I need to duplicate the grbl logo image too?  It's being shared across two plugins I manage.

That's why I pushed back seeking more details.  

And I completely overlooked my external image link.

2022-02-26 19:37 UTC, jneilliii commented on _plugins/ServoSpindle.md
> +![grbl](https://user-images.githubusercontent.com/1299716/147993411-7005d1bb-53bf-4277-9e09-5022b40ccc0b.png)
I've been told prior to doing reviews that yes, the images should be duplicated. For example I use the same paypal/patreon image in every plugin and have included it in each plugin's individual asset folder.

2022-02-28 01:21 UTC, synman commented on _plugins/ServoSpindle.md
> +![grbl](https://user-images.githubusercontent.com/1299716/147993411-7005d1bb-53bf-4277-9e09-5022b40ccc0b.png)
really fixed this time

2022-02-28 03:40 UTC, jneilliii approved these changes
Don't forget to release your 0.1.0 version on GitHub....

2022-02-28 03:44 UTC, merged