Add CalibrationTools plugin
OctoPrint/plugins.octoprint.org pull request #1005
Opened 2022-02-09 07:19 UTC by SergiuToporjinschi

Adding CalibrationTools plugin.

2022-02-09 07:55 UTC, cp2004 commented
What's the difference between this plugin and 'Calibration Companion'?

https://plugins.octoprint.org/plugins/calibrationcompanion/

Does your plugin do anything special/different or unique?

2022-02-09 08:10 UTC, SergiuToporjinschi commented
I did not know that there is another calibration plugin. But because you pointed on that, I can see that it does not having x-y-z steps calibration it has only steps for extruder.

2022-02-11 05:25 UTC, SergiuToporjinschi commented
Hi,
Just let me know if i have to change soething.
Thank you!
Have a nice day!

2022-02-12 03:58 UTC, jneilliii requested changes
Please see my comments and adjust accordingly.

2022-02-12 03:58 UTC, jneilliii commented on _plugins/CalibrationTools.md
> +archive: https://github.com/SergiuToporjinschi/OctoPrint-CalibrationTools/archive/master.zip
incorrect URL, should be `https://github.com/SergiuToporjinschi/OctoPrint-CalibrationTools/archive/master.zip`

2022-02-12 03:58 UTC, jneilliii commented on _plugins/CalibrationTools.md
> +  python: ">=3,<4"
doesn't match what's defined in your init.py file [here](https://github.com/SergiuToporjinschi/OctoPrint-CalibrationTools/blob/82ede19af44d2086dfa578e0901393d5ee14f656/octoprint_CalibrationTools/__init__.py#L125).

2022-02-12 03:58 UTC, jneilliii commented on _plugins/CalibrationTools.md
> +    https://github.com/SergiuToporjinschi/OctoPrint-CalibrationTools/archive/master.zip
same as above, incorrect URL.

2022-02-12 11:58 UTC, SergiuToporjinschi commented on _plugins/CalibrationTools.md
> +archive: https://github.com/SergiuToporjinschi/OctoPrint-CalibrationTools/archive/master.zip
Hi, Sorry but for me, the link posted by you is the same as I have in line 15 and for me both links are triggering an download of that archive.
or you are referring to the source url ? should get me to the source archive?

2022-02-12 15:32 UTC, jneilliii commented on _plugins/CalibrationTools.md
> +archive: https://github.com/SergiuToporjinschi/OctoPrint-CalibrationTools/archive/master.zip
Oh sorry, I copied/pasted but didn't adjust. It should be `https://github.com/SergiuToporjinschi/OctoPrint-CalibrationTools/archive/main.zip`

2022-02-12 15:35 UTC, jneilliii commented
@SergiuToporjinschi I didn't know that GitHub was redirecting master.zip to the correct main.zip, but it's best to set it to what it actually is, which is based on your branch name `main`. I've added a comment above with corrected URL, sorry for the confusion.

2022-02-13 07:26 UTC, SergiuToporjinschi commented
> 
Yes, I think they just changed the name of the default branch and now they are just keeping a backward compatibility. But like you said is better if we are using the new naming.

2022-02-13 08:25 UTC, jneilliii approved these changes

2022-02-13 08:25 UTC, merged