Added plugin psucontrol_fritz
OctoPrint/plugins.octoprint.org pull request #1053
Opened 2022-04-27 19:20 UTC by not-na

This adds a sub-plugin to the PSU Control plugin adding support for FRITZ!Box/FRITZ!Dect smart home devices.

2022-04-27 20:17 UTC, kantlivelong requested changes
Just two things to adjust.

https://github.com/not-na/OctoPrint-PSUControl-Fritz/blob/4d59a10d7f507ef960e0074a6a7dfdceb19a75db/octoprint_psucontrol_fritz/__init__.py#L146

2022-04-27 20:17 UTC, kantlivelong commented on _plugins/psucontrol_fritz.md
> +- tplink
Might want to adjust this :smirk:

2022-04-27 21:06 UTC, cp2004 commented
RE: https://github.com/not-na/OctoPrint-PSUControl-Fritz/blob/4d59a10d7f507ef960e0074a6a7dfdceb19a75db/octoprint_psucontrol_fritz/__init__.py#L57

Will this end up logging usernames and passwords? That is not really what we would want happening and is a security problem. Log files are designed to be shared in case of a problem.

2022-04-27 21:12 UTC, kantlivelong commented
> RE

Good catch. Note that I actually do (and thus this fork) log that with [DEBUG](https://github.com/not-na/OctoPrint-PSUControl-Fritz/blob/4d59a10d7f507ef960e0074a6a7dfdceb19a75db/octoprint_psucontrol_fritz/__init__.py#L51) but since this is INFO definitely worth filtering.

2022-04-27 22:38 UTC, not-na commented on _plugins/psucontrol_fritz.md
> +- tplink
Oops, sorry. I overlooked that while adjusting the description. I'll fix that right now.

2022-04-27 22:43 UTC, not-na commented
I've fixed the logging issue. It's probably an artifact of when I was debugging some issues while creating a session due to an outdated dependency.

2022-04-28 12:57 UTC, kantlivelong approved these changes

2022-04-28 13:04 UTC, merged