Add mkswifisdcard plugin
OctoPrint/plugins.octoprint.org pull request #1095
Opened 2022-07-31 15:19 UTC by om2804

2022-07-31 21:08 UTC, jneilliii requested changes
Quick question @om2804, where is `printer` defined in your plugin? I see multiple references to it so a little confused how that relates to `self._printer` in the scope of the plugin. 

Only other real issue I see on first look is that you are missing a [software update hook](https://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#octoprint-plugin-softwareupdate-check-config) to allow users to get notified of new releases as they are made available on your repository. Which also means you need to make sure with new versions that you create a new release with a tag that matches the plugin_version defined in setup.py. So you will also need one for 1.0.0 as first release.

2022-08-01 11:14 UTC, om2804 commented
> Quick question @om2804, where is `printer` defined in your plugin? I see multiple references to it so a little confused how that relates to `self._printer` in the scope of the plugin.

printer send to handler hook "custom_upload_to_sd" as argument

2022-08-01 11:34 UTC, cp2004 commented
You always need to specify a timeout on network requests to avoid any problems with it hanging infinitely (https://github.com/om2804/octoprint_mkswifisdcard/blob/main/octoprint_mkswifisdcard/__init__.py#L72).

Some error handling and reporting problems to the user could be required as well. Network requests are not always guaranteed to succeed.

2022-08-01 15:06 UTC, jneilliii commented
> printer sent to handler hook "custom_upload_to_sd" as argument

ah, totally missed that. my apologies. once these other changes have been completed we can move forward with merging this. Please make sure to address Charlie's concerns as well relative to request timeout.

2022-08-01 16:30 UTC, om2804 commented
@cp2004 @jneilliii 
I made changes in all comments

2022-08-01 18:11 UTC, jneilliii requested changes
One little change to your template, and you're still missing the 1.0.0 tagged release [here](https://github.com/om2804/octoprint_mkswifisdcard/releases).

2022-08-01 18:11 UTC, jneilliii commented on _plugins/mkswifisdcard.md
> +archive: https://github.com/om2804/octoprint_mkswifisdcard/archive/master.zip
URL should be `https://github.com/om2804/octoprint_mkswifisdcard/archive/main.zip`. to match the branch name on GitHub.

2022-08-01 20:18 UTC, jneilliii approved these changes

2022-08-01 20:18 UTC, jneilliii approved these changes

2022-08-01 20:26 UTC, merged