Hint about archive url and branching strategy.
OctoPrint/plugins.octoprint.org pull request #1099
Opened 2022-08-10 18:19 UTC by arekm

As explained in change itself.

2022-08-11 14:13 UTC, cp2004 requested changes
Readability & link changes, see individual comments.

2022-08-11 14:13 UTC, cp2004 commented on help/registering/index.md
> +      * Keep ``archive:`` URL **always pointing to latest release**. ``OctoPrint`` uses that link for initial installation
```suggestion
      * Make sure the ``archive`` URL is **always pointing to the latest release**. OctoPrint uses that URL for initial installation
```
'Keep' doesn't fit with the context of creating a new registration, and there's no need for 'OctoPrint' to be monospaced.

2022-08-11 14:13 UTC, cp2004 commented on help/registering/index.md
> +        of plugin from [Plugin Manager](https://github.com/foosel/OctoPrint/wiki/Plugin:-Plugin-Manager) (regardless
```suggestion
        of the plugin from the [Plugin Manager](https://github.com/foosel/OctoPrint/wiki/Plugin:-Plugin-Manager) (regardless
```
Also, the link added here doesn't go anywhere.

2022-08-11 14:13 UTC, cp2004 commented on help/registering/index.md
> +        of version shown there). If using ``github`` and URL points to ``PROJECT/archive/master.zip`` adjust your
```suggestion
        of the version shown there). If you are using GitHub and the URL points to ``<project url>/archive/master.zip`` adjust your
```

I feel like this should be more generic - it does not have to be master, it could be absolutely anything you've named the branch.

2022-08-11 16:24 UTC, foosel commented on help/registering/index.md
> +        of plugin from [Plugin Manager](https://github.com/foosel/OctoPrint/wiki/Plugin:-Plugin-Manager) (regardless
The "the"s are still missing @arekm

2022-08-11 16:28 UTC, arekm commented on help/registering/index.md
> +        of plugin from [Plugin Manager](https://github.com/foosel/OctoPrint/wiki/Plugin:-Plugin-Manager) (regardless
Added, thanks.

2022-08-12 18:25 UTC, cp2004 approved these changes

2022-08-12 20:32 UTC, merged