Updating OctoEverywhere Plugin Images
OctoPrint/plugins.octoprint.org pull request #1106
Opened 2022-09-19 18:39 UTC by QuinnDamerell

Adding an image and updating the style of the existing ones.

2022-09-19 19:20 UTC, cp2004 requested changes

2022-09-19 19:26 UTC, QuinnDamerell commented
Great catch! I looked at those URL 3 times and still missed it. :)

2022-09-19 19:52 UTC, QuinnDamerell reviewed
Fixed up!

2022-09-20 15:19 UTC, jneilliii approved these changes

2022-09-20 15:19 UTC, merged

2022-09-20 15:35 UTC, QuinnDamerell commented
Thanks @jneilliii and @cp2004 !