Added plugin nexus_ai
OctoPrint/plugins.octoprint.org pull request #1109
Opened 2022-09-29 09:56 UTC by fiber-punk

2022-10-01 20:50 UTC, jneilliii requested changes
couple of small changes required here, and then in your repo the GitHub user is incorrect [here](https://github.com/fiberpunk1/OctoPrint-Nexus-AI/blob/da7b398a1e3c84c2971af91c7291a583734d1426/octoprint_nexus_ai/__init__.py#L165), should be fiberpunk1 I think? 

Also, you need to create a release in your GitHub repo for the plugin that matches the version number specified in setup.py. Then for updating everyone's instance you update that version number in setup.py and create new release with same version number tag.

2022-10-01 20:50 UTC, jneilliii commented on _plugins/nexus_ai.md
> +- to your plugin
questionable tag, remove

2022-10-01 20:50 UTC, jneilliii commented on _plugins/nexus_ai.md
> +date: 2020-09-29
correct release date

2022-10-02 23:19 UTC, fiber-punk commented on _plugins/nexus_ai.md
> +date: 2020-09-29
Thanks.
I will make modifications, and then send a  pull request with fiberpunk1.

2022-10-03 02:56 UTC, jneilliii commented
closing, changes seem to be re-PR'd as #1111

2022-10-03 02:56 UTC, closed without merging