Restrict versions to reflect latest version
OctoPrint/plugins.octoprint.org pull request #1183
Opened 2023-04-24 16:51 UTC by cameroncros

2023-04-24 17:55 UTC, jneilliii requested changes

2023-04-24 17:55 UTC, jneilliii commented on _plugins/discordremote.md
> +date: 2023-04-25
as the bot already picked up...you aren't suppose to change the date.

2023-04-24 23:02 UTC, cameroncros commented on _plugins/discordremote.md
> +date: 2023-04-25
Right, didnt see the bot result, have fixed that now.

2023-04-25 00:51 UTC, jneilliii approved these changes

2023-04-25 00:52 UTC, merged