Add plugin Connect And Print
OctoPrint/plugins.octoprint.org pull request #1185
Opened 2023-04-26 19:01 UTC by Maxinger15

This plugin connects octoprint automaticlly to your printer if you upload a file.
This is useful if you turn of your printer put octoprint is powered on constantly.

2023-04-27 03:52 UTC, jneilliii requested changes
1. Should probably add some content below the template block that explains a little more in depth what the plugin does, including 2 minute timeout, etc. 

2. Your plugin is basically a single file plugin, so you don't need `octoprint.plugin.AssetPlugin`, `octoprint.plugin.SimpleApiPlugin`, or `octoprint.plugin.TemplatePlugin` [here](https://github.com/Maxinger15/connectandprint/blob/c2f70364266152a4a449dd589569503902f1cb8b/connect_and_print.py#L8-L11) but would want to add `octoprint.plugin.RestartNeedingPlugin`.

3. Your plugin structure in the repo is not going to work as-is to install. The simplest option would be to register as a single file plugin by using `https://raw.githubusercontent.com/Maxinger15/connectandprint/master/connect_and_print.py` as the archive URL after making the changes mentioned in 2 above. Otherwise, you would need to rename the connect_and_print.py file to `__init__.py` and move it into a subfolder named connectandprint. Then your setup.py file needs to be updated, it's missing a lot of stuff that should be in there to properly install. I'd recommend copying the hello world example one from [here](https://github.com/OctoPrint/Plugin-Examples/blob/master/helloworld/setup.py) and replace all the pieces appropriately if you decide to go that route. 

4. I recommend you test the install by removing it from your OctoPrint instance and copying/pasting the `archive` URL into Plugin Manager > Get More > ...from URL and click install to validate yourself. 

5. We highly encourage you include a [software update hook](https://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#hooks) in your plugin so users are able to receive new version as you release them on GitHub. Related to that, you'll also need to create a new release with tag that matches your initial 1.0.0 version.

2023-04-27 04:00 UTC, jneilliii commented
On a side note, on a linux machine the portlister plugin can automatically connect the printer when it is detected by the OS.

2023-04-28 13:25 UTC, Maxinger15 commented
Thank you very much for the valueable feedback @jneilliii. I will implement the changes soon.

2023-04-29 04:09 UTC, jneilliii requested changes

2023-04-29 04:09 UTC, jneilliii commented on _plugins/connectandprint.md
> +id: connectandprint
plugin identifiers for single file plugins are based on the filename, so you should update this id to match `connect_and_print` or rename the file and update the `archive` URL to match. whichever approach you go with you then need to change `auto_connect_and_print` [here](https://github.com/Maxinger15/connectandprint/blob/4442b9837e6623e429565058753790f06d6207a2/connect_and_print.py#L39) to match as well.

you may also want to add a `__plugin_description__`, `__plugin_author__`, `__plugin_url__`, and `__plugin_license__` [control properties](https://docs.octoprint.org/en/master/plugins/controlproperties.html) to your py file to fill in the gaps since you're not using the setup.py file, otherwise these items remain blank I think.

![image](https://user-images.githubusercontent.com/5249455/235282795-9f774b78-5c87-45e4-9091-20edce6196e4.png)

2023-04-29 04:10 UTC, jneilliii commented on _plugins/connectandprint.md
> +id: connectandprint
oh, and you also need to create the tag and release for 1.0.0 on your repo.

2023-04-29 09:04 UTC, Maxinger15 commented
I applied the changes accordingly to your suggestions.

2023-04-29 14:38 UTC, jneilliii approved these changes

2023-04-29 14:39 UTC, merged

2023-06-05 19:24 UTC, AstroMelly commented
Hi @Maxinger15 - just to let you know that it looks like this plugin fails to update for me.  Not sure if you can help with this or maybe it's me!  I'm pretty new to OctoPrint and 3D Printing but I am also a programmer so thought I would send this through to you.

Here's the error from the octoprint log file ~/.octoprint/logs//plugin_softwareupdate_console.log:

2023-06-05 15:50:26,258   /home/pi/oprint/bin/python -m pip --disable-pip-version-check install https://raw.githubusercontent.com/Maxinger15/connectandprint/1.2.0/connectandprint.py --no-cache-dir
2023-06-05 15:50:28,835 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2023-06-05 15:50:28,837 > Collecting https://raw.githubusercontent.com/Maxinger15/connectandprint/1.2.0/connectandprint.py
2023-06-05 15:50:28,838 > Downloading https://raw.githubusercontent.com/Maxinger15/connectandprint/1.2.0/connectandprint.py (3.2 kB)
2023-06-05 15:50:28,842 ! ERROR: Cannot unpack file /tmp/pip-unpack-0l6n6qdc/connectandprint.py (downloaded from /tmp/pip-req-build-6i9jbhbf, content-type: text/plain; charset=utf-8); cannot detect archive format
2023-06-05 15:50:28,843 ! ERROR: Cannot determine archive format of /tmp/pip-req-build-6i9jbhbf

2023-06-05 21:09 UTC, Maxinger15 commented
hi @AstroMelly ,
yeah this is a bug in that version.
Please remove the plugin and install it again.
More info here: https://github.com/Maxinger15/connectandprint/issues/6

2023-06-06 06:55 UTC, AstroMelly commented
Got it.  Thank you.  Also tracking the reported OctoPrint bug for eTag error post plugin install.  

Thanks again!