adopt PrintJobHistory plugin
OctoPrint/plugins.octoprint.org pull request #1248
Opened 2023-11-27 18:20 UTC by dojohnso

Updated references to point to my fork of the repo for v1.17.1 (previously 1.17.0). The release includes a couple bug fixes people were waiting for, otherwise it's the same. 

https://github.com/dojohnso/OctoPrint-PrintJobHistory/releases/tag/1.17.1

Let me know if I missed anything or need to do anything else. Thank you!

2023-11-27 18:29 UTC, jneilliii requested changes
Just a minor change necessary, date should remain the same.

2023-11-27 18:29 UTC, jneilliii commented on _plugins/PrintJobHistory.md
> +date: 2023-11-27
you shouldn't change this date, please change it back to the original.

2023-11-27 18:40 UTC, cp2004 requested changes

2023-11-27 18:40 UTC, cp2004 commented on _data/update_check_overlays.yaml
> +  user: dojohnso
You need to add the pip URL as well, otherwise existing users will be prompted to upgrade to a new version, but it tries to download from the old location still.

2023-11-27 18:40 UTC, cp2004 commented on _data/notices.yaml
> +    settings. The release notes of the version by the new maintainer can be found at the "Read more..." link below.
This is less a comment that needs addressing here, but the wording used in these notices is outdated since the update check overlays (when configured properly) allow for updates to be redirected to the new version without needing to reinstall. It's not wrong, so no harm in keeping it in.

2023-11-27 19:30 UTC, dojohnso commented on _data/notices.yaml
> +    settings. The release notes of the version by the new maintainer can be found at the "Read more..." link below.
@cp2004 I'd probably rather let people keep their current data rather than uninstall and reinstall to avoid loss of history. Should I just remove this text? Or is there better text to use today?

2023-11-27 20:15 UTC, jneilliii commented on _data/notices.yaml
> +    settings. The release notes of the version by the new maintainer can be found at the "Read more..." link below.
I'd probably just make it something like this:

```
Version 1.17.1 of this plugin is available from a new maintainer. The release notes of the version by the new maintainer can be found at the "Read more..." link below.
```

2023-11-27 20:16 UTC, jneilliii commented
Looks like GitHub is having issues right now, so once it catches up and the additional commit(s) show up with these changes we can finalize the adoption.

2023-11-27 20:26 UTC, jneilliii requested changes

2023-11-27 20:26 UTC, jneilliii commented on _data/update_check_overlays.yaml
> +  pip: https://github.com/dojohnso/OctoPrint-PrintJobHistory/archive/{target_version}.zip
This is a little different with OllisGit plugins, similar to what cp2004 does, and the url is to an attached zip asset called main.zip instead of the source zip file, so would need to be like this I think.
```
  pip: https://github.com/dojohnso/OctoPrint-PrintJobHistory/releases/download/{target_version}/main.zip
```

2023-11-27 20:57 UTC, dojohnso commented on _data/update_check_overlays.yaml
> +  pip: https://github.com/dojohnso/OctoPrint-PrintJobHistory/archive/{target_version}.zip
ok yeah that works. I just copied what I saw from before, figured would change as needed. Thanks for reviewing all this so quickly!

2023-11-27 21:33 UTC, cp2004 commented on _data/update_check_overlays.yaml
> +  pip: https://github.com/dojohnso/OctoPrint-PrintJobHistory/archive/{target_version}.zip
Yeah since you've got the actions working to make the releases, that makes sense. I do it this way to have the version number automatically bumped based on the tag, not sure what OllisGit did it for but definitely worth fully understanding. People will very quickly come running if you get it wrong!

2023-11-27 21:34 UTC, cp2004 approved these changes
My comments resolved, don't want to hold up the process so back over to @jneilliii :)

2023-11-27 22:46 UTC, jneilliii commented on _data/update_check_overlays.yaml
> +  pip: https://github.com/dojohnso/OctoPrint-PrintJobHistory/archive/{target_version}.zip
Assuming they are working on @dojohnso's fork. I do see build failures on the actions though. Going to go ahead and approve and merge the adoption as that is not specific to the plugin repository listing and as 

https://github.com/dojohnso/OctoPrint-PrintJobHistory/actions/runs/7008953602/job/19066379869#step:11:26

IIRC correctly the reason OllisGit was doing releases that way was to get download stats of the asset download for the readme badges, which doesn't work with source zip downloads.

2023-11-27 22:46 UTC, jneilliii approved these changes

2023-11-27 22:51 UTC, merged

2023-11-27 23:28 UTC, dojohnso commented
Thanks again everyone! FYI the abandoned notice still pops up in addition to the update. I'm sure people will figure it out, just wanted to mention it in case it got overlooked. I'm not sure of your process of course so just putting it out there.  🙂

2023-11-28 00:14 UTC, jneilliii commented
Yeah, the notices typically go out quickly, while the software update caches the list of available versions for a day I think. You can always use software update settings and force check for updates to bypass the cache.

![image](https://github.com/OctoPrint/plugins.octoprint.org/assets/5249455/4052e7f9-ef60-4f36-9e82-fe2deb5972ec)

2023-11-30 16:34 UTC, dojohnso commented
Just curious when this abandoned notice and status goes away? 
![image](https://github.com/OctoPrint/plugins.octoprint.org/assets/294549/6db4609a-3c51-4747-a269-e2f776f9d667)
![image](https://github.com/OctoPrint/plugins.octoprint.org/assets/294549/c75cbfed-fa53-4504-bcdc-9ef6077ab688)

2023-11-30 16:46 UTC, jneilliii commented
Ah, you didn't remove the abandoned line from the PrintJobHistory.md file. That was my mistake for missing it during review. Will be updated once this PR passes checks and gets merged.

https://github.com/OctoPrint/plugins.octoprint.org/pull/1249

2023-11-30 18:46 UTC, dojohnso commented
Ok sounds good, thank you! I saw that line in there but wasn't sure who managed it so I left it alone. Makes sense and again I appreciate everyone's help getting this moved. I've already had great feedback and interactions with users who are excited to see development pick up on it again. Cheers!