First create PiNozCam.md
OctoPrint/plugins.octoprint.org pull request #1285
Opened 2024-03-04 03:42 UTC by DrAlexLiu

2024-03-04 03:52 UTC, DrAlexLiu commented
First create the PiNozCam and publish

2024-03-04 04:20 UTC, jneilliii requested changes
Is there a recommended pi version for handling the AI image processing? Might be a good idea to include that here in the plugin listing. 

There are a couple of issues. [here](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/blob/f686a58c0c09c2c7506486e4eb41711e5aadbc5c/octoprint_pinozcam/__init__.py#L436) needs to match your plugins identifier from setup.py. Change `updateplugindemo` to `pinozcam`. Same is true for the id in your plugin listing md file, as well as the filename itself. `PiNozCam.md` should be named `pinozcam.md`.

2024-03-04 04:20 UTC, jneilliii commented on _plugins/PiNozCam.md
> +id: PiNozCam
should be `pinozcam` to match setup.py

2024-03-04 04:25 UTC, jneilliii commented
Couple of other house-keeping items. Delete the folders [OctoPrint_PiNozCam.egg-info](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/tree/f686a58c0c09c2c7506486e4eb41711e5aadbc5c/OctoPrint_PiNozCam.egg-info) and [__pycache__](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/tree/f686a58c0c09c2c7506486e4eb41711e5aadbc5c/octoprint_pinozcam/__pycache__), they shouldn't be included in your plugin's repo and are typically added to .gitignore to prevent them from being uploaded.

2024-03-04 04:28 UTC, jneilliii commented
you may also want to include a screenshot of the tab, it's highly recommended.

2024-03-06 06:12 UTC, jneilliii approved these changes

2024-03-06 06:14 UTC, DrAlexLiu commented
Thanks for approval.

2024-03-06 06:19 UTC, merged