Added updated plugin version of Fan Speed Slider Plugin
OctoPrint/plugins.octoprint.org pull request #1298
Opened 2024-05-28 12:56 UTC by mival

2024-05-28 15:19 UTC, jneilliii requested changes
should probably include all contributors to authors since this is a fork of a fork and you need to rename the file `_plugins/FanSpeedSlider.md` to `plugins/fanspeedslider.md` to match the plugin_identifier.

2024-05-28 15:19 UTC, jneilliii commented on _plugins/FanSpeedSlider.md
> +author: mival
would be nice to credit all the authors here as an array. change `author: mival` to
```
authors:
- mival
- jneilliii
- czM1K3
- ntoff
```

You also need to update the software update check line [here](https://github.com/mival/OctoPrint-FanSpeedSlider/blob/704c37d853b86f7b5241ba4748217104fd4f7422/octoprint_fanspeedslider/__init__.py#L141) to your github username.

2024-05-29 07:05 UTC, mival commented on _plugins/FanSpeedSlider.md
> +author: mival
@jneilliii thank you for review, I updated code and plugin info

2024-05-29 22:32 UTC, jneilliii approved these changes

2024-05-29 22:35 UTC, jneilliii requested changes
sorry I missed this before @mival but update this URL and one last thing on the plugin's repo. You need to create a release tagged 0.2.3 to match the plugin version identified in setup.py.

2024-05-29 22:35 UTC, jneilliii commented on _plugins/fanspeedslider.md
> +archive: https://github.com/mival/OctoPrint-FanSpeedSlider/archive/main.zip
technically should be 
```
archive: https://github.com/mival/OctoPrint-FanSpeedSlider/archive/master.zip
```
to match the branch name.

2024-05-31 06:42 UTC, mival commented on _plugins/fanspeedslider.md
> +archive: https://github.com/mival/OctoPrint-FanSpeedSlider/archive/main.zip
@jneilliii no problem, but rather I renamed master -> main to keep with new naming convention. Hopefully I also renamed all occurrences in repo.

2024-05-31 06:48 UTC, mival commented
@jneilliii and hopefully I created tag for version and also release for that tag.

2024-05-31 15:50 UTC, jneilliii approved these changes

2024-05-31 15:51 UTC, merged