Dashboard plugin handover
OctoPrint/plugins.octoprint.org pull request #637
Opened 2020-09-27 10:32 UTC by j7126

Updates for the dashboard plugin transferring to new maintainers.

2020-09-27 10:32 UTC, j7126 commented
Resolve abandoned plugin issue #628

2020-09-27 21:14 UTC, jneilliii commented
Hey guys, thanks for adopting this plugin. Just wanted to ask a question in regard to the author. Historically the new maintainers have been appended to the author field so I wanted to check with you first to see if that was intentional or not?

2020-09-27 21:17 UTC, jneilliii commented
One other thing. Would you guys mind migrating your images into the PR as well rather than linking those images to github? This is a new thing that we're trying to clean up to limit GDPR related concerns.

2020-09-28 03:22 UTC, jneilliii requested changes
@j7126 relative to the GDPR related concerns I mentioned, please see the relative comments and associated changes. Basically just need to get those images copied to `assets/img/plugins/dashboard/` on your PR and update the references in the markdown file as noted please. Thanks for the help on this.

2020-09-28 03:22 UTC, jneilliii commented on _plugins/dashboard.md
> +- url: https://github.com/j7126/OctoPrint-Dashboard/raw/master/screenshot.png
update to the following and copy relative screenshot.
```
/assets/img/plugins/dashboard/screenshot.png
```

2020-09-28 03:22 UTC, jneilliii commented on _plugins/dashboard.md
> +- url: https://github.com/j7126/OctoPrint-Dashboard/raw/master/screenshot-theme.png
update to the following and copy relative screenshot.
```
/assets/img/plugins/dashboard/screenshot-theme.png
```

2020-09-28 03:22 UTC, jneilliii commented on _plugins/dashboard.md
> +- url: https://github.com/j7126/OctoPrint-Dashboard/raw/master/screenshot-theme2.png
update to the following and copy relative screenshot.
```
/assets/img/plugins/dashboard/screenshot-theme2.png
```

2020-09-28 03:22 UTC, jneilliii commented on _plugins/dashboard.md
> +featuredimage: https://github.com/j7126/OctoPrint-Dashboard/raw/master/screenshot.png
update to the following
```
/assets/img/plugins/dashboard/screenshot.png
```

2020-09-28 03:22 UTC, jneilliii commented on _plugins/dashboard.md
> +![Screenshot](https://github.com/j7126/OctoPrint-Dashboard/raw/master/screenshot.png)
update to the following
```
![Screenshot](/assets/img/plugins/dashboard/screenshot.png)
```

2020-09-28 03:22 UTC, jneilliii commented on _plugins/dashboard.md
> +![Screenshot](https://github.com/j7126/OctoPrint-Dashboard/raw/master/screenshot-theme.png)
update to the following
```
![Screenshot](/assets/img/plugins/dashboard/screenshot-theme.png)
```

2020-09-28 03:24 UTC, j7126 commented
Will do. I am just preparing to redo all the screenshots because they are from an older version of the plugin.

2020-09-28 03:42 UTC, jneilliii commented
Oh, my bad. I was trying to help you out a little and do these changes for you, and just added to this PR. I apologize if this breaks something in the git workflow/commit history.

2020-09-28 07:15 UTC, j7126 commented
Added new screenshots.
Should be ready to merge now

2020-09-28 16:22 UTC, jneilliii approved these changes

2020-09-28 16:22 UTC, merged