Added plugin Mattacloud Beta
OctoPrint/plugins.octoprint.org pull request #663
Opened 2020-10-17 17:13 UTC by dougbrion

Adding first release of Mattacloud Beta (v0.1.0) to the OctoPrint Plugin Repository.

Many cups of tea and biscuits have been consumed in producing this initial beta.
The following features have been implemented:

- Profile creation with account management
- Printer authentication workflow 
- The creation and deletion of printers
- Remote file management and file upload
- Live temperature data stream
- Control through GUI of temperatures, axis movement, extruder movement, flow rate, feed rate and more
- Storage and viewing of print history for each printer
- Capture of images during prints with live updates
- WebRTC video stream of Python 3 OctoPrint users

2020-10-17 19:59 UTC, jneilliii requested changes
@dougbrion Please see comment. Once that's complete I'll feel comfortable in merging.

2020-10-17 19:59 UTC, jneilliii commented on _plugins/mattacloud.md
> +1. [Sign up](https://cloud.mattalabs.com/accounts/signup/) to the **Mattacloud** free beta trial. If you already have, just [login](https://cloud.mattalabs.com/accounts/login/). (Trial lasts for the
I think you should mention that once the public beta has expired there is no free tier subscription service here, best I can tell.

2020-10-18 17:05 UTC, dougbrion commented on _plugins/mattacloud.md
> +1. [Sign up](https://cloud.mattalabs.com/accounts/signup/) to the **Mattacloud** free beta trial. If you already have, just [login](https://cloud.mattalabs.com/accounts/login/). (Trial lasts for the
Will update with better description and info, the beta trial will convert into a free tier subscription service so will make this more clear!

2020-10-18 17:26 UTC, cp2004 commented
> WebRTC video stream of Python 3 OctoPrint users
Shameless plug by me: Be sure to link to [OctoPrint Upgrade To Python 3](https://github.com/cp2004/Octoprint-Upgrade-To-Py3) when someone asks why they can't get WebRTC streaming. Because believe me, they won't read. It won't be as bad as the wifi status plugin, since this *works* on Python 2, just not everything. Someone will still ask...

2020-10-18 17:30 UTC, jneilliii approved these changes

2020-10-18 17:31 UTC, merged