support python 3 using octoprint >= 1.4
OctoPrint/plugins.octoprint.org pull request #690
Opened 2020-11-19 14:00 UTC by ChristophSchranz

2020-11-19 16:55 UTC, jneilliii requested changes
@ChristophSchranz please see comments.

2020-11-19 16:55 UTC, jneilliii commented on _plugins/preprintservice.md
> +  - 1.4.0
@ChristophSchranz I don't this this is going to do what you expect and I don't believe is necessary. If they are running older versions of OctoPrint then they will be utilizing the python 2.7 side of things, which you are tagging as compatible. When there is only 1 version here in this list, then it is any version newer than that listed version will be supported. The python compatibility flag below should be enough. If there are more than one versions listed here than only those versions will be able to install the plugin and run.

I think you should just remove the `- 1.4.0` part.

2020-11-20 07:40 UTC, ChristophSchranz commented on _plugins/preprintservice.md
> +  - 1.4.0
Did it, thanks!

2020-11-20 15:57 UTC, jneilliii approved these changes

2020-11-20 15:58 UTC, merged