Compatibility update
OctoPrint/plugins.octoprint.org pull request #716
Opened 2020-12-17 09:24 UTC by LMS0815

Just fixed tome code to ensure compatibility with OctoPrint 1.5.+

2020-12-17 09:57 UTC, LMS0815 commented
I am lost. Please tell me what to amend...

2020-12-17 17:23 UTC, jneilliii requested changes
please see comments and adjust accordingly, thanks.

2020-12-17 17:23 UTC, jneilliii commented on _plugins/OctoPrint-hueCommands.md
> +date: 2020-12-17
never change the date from initial submission date

2020-12-17 17:23 UTC, jneilliii commented on _plugins/OctoPrint-hueCommands.md
> +- alt: Plugin Settings
Image needs to be included in `/assets/img/plugins/hueCommands/huecommands_settings.png` as part of this PR rather than linking to your github page. This helps us out with potential GDPR related issues.

```
screenshots:
- url: /assets/img/plugins/hueCommands/huecommands_settings.png
  alt: Plugin Settings
```

2020-12-17 17:23 UTC, jneilliii commented on _plugins/OctoPrint-hueCommands.md
> +[![paypal](https://www.paypalobjects.com/digitalassets/c/website/marketing/emea/de/de/logo-center/M2_Logo_02.jpg)](https://paypal.me/stonehome/5 "PayPal.me")
similar to above comment, we need the image to be part of your PR submission, save image to `/assets/img/plugins/hueCommands/M2_Logo_02.jpg` and update reference.

2020-12-17 17:29 UTC, jneilliii commented
I'm also not sure on your compatibility list for 1.4.+ and 1.5.+. I'm not super familiar with PEP440 format, but I think it should be 1.4.* and 1.5.*. Maybe @cp2004 knows for sure.

2020-12-17 17:35 UTC, cp2004 commented
> I'm also not sure on your compatibility list for 1.4.+ and 1.5.+. I'm not super familiar with PEP440 format, but I think it should be 1.4.* and 1.5.*. Maybe @cp2004 knows for sure.

Correct, PEP440 would be 1.5.* - https://www.python.org/dev/peps/pep-0440/#compatible-release

However, I don't know what the plugin repo accepts - it can't be specifically PEP440, otherwise defining a single version as the minimum wouldn't work, there is no `==` part.

2020-12-18 09:05 UTC, LMS0815 commented
I tried for HOURS to get this working.
I give up and quit updating details of my plugin.

2020-12-18 09:05 UTC, closed without merging

2020-12-18 09:10 UTC, cp2004 commented
Hey, you were almost there! I was about to jump in an suggest the only change required:

```yaml
compatibility:
  octoprint:
  - 1.5.0
```
When it says list value, it cannot be in a single field and instead must use the list notation in YAML style.

The documentation has a good explanation of this, so you can understand the different data types:
https://docs.octoprint.org/en/master/configuration/yaml.html

2020-12-18 09:54 UTC, LMS0815 commented
Thank you. I started YESTERDAY amending just the Line with the OctoPrint version you highlighted. 

But committing did not work.

All of a sudden the whole document seems to be wrong.
I more or less spend 16 hours trying to inform OctoPrint repository, that the plugin is updated and known to be working with OctoPrint v1.5.x

As the installed base is very small anyway, I have the strong feeling, that this effort is wasted time.