Add v0.1.0 directory listing for https://print-nanny.com
OctoPrint/plugins.octoprint.org pull request #724
Opened 2020-12-26 07:12 UTC by leigh-johnson

2020-12-26 08:48 UTC, jneilliii requested changes
Thanks for your submission @leigh-johnson only a couple of things that we need fixed up before acceptance. Please see the comments below. 

Also, could you clarify in your description if there is going to be a subscription tier eventually and if so what those tiers will be? ie Will there be a free tier available to users once the product is out of closed Beta?

2020-12-26 08:48 UTC, jneilliii commented on _plugins/octoprint_nanny.md
> +archive: https://github.com/bitsy-ai/octoprint-nanny-plugin/archive/master.zip
invalid URL, should be main.zip instead of master.zip. This is because of github's new default branch named master.

2020-12-26 08:48 UTC, jneilliii commented on _plugins/octoprint_nanny.md
> +id: octoprint_nanny
id needs to match your repos plugin_identifier [here](https://github.com/bitsy-ai/octoprint-nanny-plugin/blob/e6b0bf161b5b64aadfd4f8efe22a9a8896e2d1d6/octoprint_nanny/plugins.py#L279) and [here](https://github.com/bitsy-ai/octoprint-nanny-plugin/blob/e6b0bf161b5b64aadfd4f8efe22a9a8896e2d1d6/setup.py#L8), so all three places need to use the same id. You have `octoprint_nanny`, `print_nanny`, and `nanny`. Probably easiest to just make them all `octoprint_nanny`.

2020-12-26 08:48 UTC, jneilliii commented on _plugins/octoprint_nanny.md
> +license: GNU AFFERO GENERAL PUBLIC LICENSE
license doesn't match repo [here](https://github.com/bitsy-ai/octoprint-nanny-plugin/blob/e6b0bf161b5b64aadfd4f8efe22a9a8896e2d1d6/setup.py#L34).

2020-12-26 20:37 UTC, leigh-johnson commented
Thank you so much for the careful review @jneilliii! 

I don't have the exact pricing structure nailed down yet, but I hope clarifying my mission sets good expectations. I have a lot of respect and admiration for the community and ecosystem y'all support, and I want to contribute back. :heart:

2020-12-26 21:15 UTC, jneilliii requested changes
Thanks @leigh-johnson that is more up front, which is what we strive to do for these types of external services. After your changes, I'm still seeing one small thing. Please update `nanny` [here](https://github.com/bitsy-ai/octoprint-nanny-plugin/blob/e43a5baf8a85ca2ad3faa3014f01761abe793d0d/octoprint_nanny/plugins.py#L279) to be `octoprint_nanny` as well so that the update check will work properly.

2020-12-26 21:52 UTC, leigh-johnson commented
Oh goodness, thank you for catching that! I can make machines learn but still can't name things correctly. :joy: 

Just re-cut the v0.1.0 release
https://github.com/bitsy-ai/octoprint-nanny-plugin/releases/tag/v0.1.0

2020-12-27 00:25 UTC, jneilliii commented
@leigh-johnson it's still not right, showing as `nanny` it needs to be correct in the main branch, not just in release, even though browsing the same line in your link is wrong as well.

https://github.com/bitsy-ai/octoprint-nanny-plugin/blob/e2ca54ce8aca03b1ed49ae5a455fdf9b758f2a6b/octoprint_nanny/plugins.py#L279

2020-12-27 00:37 UTC, leigh-johnson commented
Oops, I apologize for that - thank you again for checking this over, especially on a holiday Saturday! I think I nailed it this time around. 

https://github.com/bitsy-ai/octoprint-nanny-plugin/blob/main/octoprint_nanny/plugins.py#L279

![9aa58843f5cef8bfbf291c53cbb4baab](https://user-images.githubusercontent.com/2601819/103161539-27025f00-4798-11eb-91a3-261bad32fe9a.jpg)

2020-12-27 00:53 UTC, jneilliii approved these changes

2020-12-27 00:53 UTC, merged