Added plugin IgnorePausedForUser
OctoPrint/plugins.octoprint.org pull request #787
Opened 2021-02-19 21:56 UTC by DavideM84

Added plugin IgnorePausedForUser

2021-02-19 22:13 UTC, cp2004 commented
We aren't accepting new plugins that aren't Python 3 compatible - please either make it Py 3 compatible or correct the listing if it is in fact Python 3 compatible.

2021-02-19 22:18 UTC, jneilliii reviewed
Concerned a little about the writing of events to the log with info rather than debug [here](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/533376f130b561232007e8c6da34eb19f4c05564/octoprint_IgnorePausedForUser/__init__.py#L28-L29) and [here](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/533376f130b561232007e8c6da34eb19f4c05564/octoprint_IgnorePausedForUser/__init__.py#L31) because file write operations should be avoided in the communication layer to avoid blocking/stuttering, so either change that to debug or thread the writes using another method please.

2021-02-19 22:18 UTC, jneilliii commented on _plugins/ignorepausedforuser.md
> +  python: ">=2.7,<3"
we no longer accept plugins in the repo that are not python 3 compatible. Looking at your plugin it appears to be specifying python 3 compatible, so this should be `">=2.7,<4"`.

2021-02-19 22:18 UTC, jneilliii commented on _plugins/ignorepausedforuser.md
> +archive: https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/archive/v1.2.2.zip
this shouldn't point to a specific release version, but the asset download url for a branch or latest version tag.

2021-02-19 23:05 UTC, DavideM84 commented on _plugins/ignorepausedforuser.md
> +  python: ">=2.7,<3"
Fixed

2021-02-19 23:06 UTC, DavideM84 commented on _plugins/ignorepausedforuser.md
> +archive: https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/archive/v1.2.2.zip
Fixed

2021-02-20 02:38 UTC, jneilliii requested changes
It appears the python version didn't get updated. The link looks good. I noticed one more thing that needs to be addressed in the comments below, sorry I missed this before.

2021-02-20 02:38 UTC, jneilliii commented on _plugins/ignorepausedforuser.md
> +  python: ">=2.7,<3"
It's still the same @DavideM84. This line should read as follows.
```
  python: ">=2.7,<4"
```

2021-02-20 02:38 UTC, jneilliii commented on _plugins/ignorepausedforuser.md
> +id: ignorepausedforuser
this id should match the name of the submitted plugin.md file (which it does) but it also should match [here](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/f4b762611b0c28c641aa4547080a353341b1ce78/setup.py#L7) and [here](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/f4b762611b0c28c641aa4547080a353341b1ce78/octoprint_IgnorePausedForUser/__init__.py#L94) in your plugin's repo. 

So the options are to adjust the `plugin_identifier` in setup.py and the dictionary name returned in the init.py file to be all lowercase or change the `id` and rename this md file to match the camel case identifier you have in your plugin.

2021-02-20 09:55 UTC, DavideM84 commented
All issues fixed. Thanks for supports.
Let's go ;)

2021-02-20 19:05 UTC, jneilliii commented
@FormerLurker/@cp2004 you think you guys could take a second look?

2021-02-20 19:20 UTC, cp2004 commented
Seems good to me, but I'll leave it to the plugin reviewers for the final decision 😄.

2021-02-20 19:21 UTC, FormerLurker commented
Sure.  Give me a couple hours.  In the middle of a difficult build.

2021-02-24 13:01 UTC, DavideM84 commented
@FormerLurker  any news ?

2021-02-24 14:02 UTC, FormerLurker commented
@DavideM84, on it, sorry for the delay.

2021-02-24 14:18 UTC, FormerLurker commented
In your ignorepausedforuser_settings.jinja2.jinja file [here](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/a8348a5b55e0045301ca6ca7ae703b994a6dc18e/octoprint_ignorepausedforuser/templates/ignorepausedforuser_settings.jinja2#L5) you are retrieving an image from Github.  This isn't an error, obviously, but consider adding the image to your project and retrieving it from there lest you get issues submitted for offline users.

This is just a question about the functionality, but [in your event handler](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/a8348a5b55e0045301ca6ca7ae703b994a6dc18e/octoprint_ignorepausedforuser/__init__.py#L67-L74), do you intend to create history even when the plugin is disabled?

Everything looks good though.  Just decide if you want to make any changes and let us know!

2021-02-24 14:43 UTC, jneilliii commented
I'm still concerned about the blocking communication layer that initially asked about. That's still a problem isn't it @FormerLurker? I realize this is only on paused from printer, but seems like it's doing a fair amount of IO [here](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/a8348a5b55e0045301ca6ca7ae703b994a6dc18e/octoprint_ignorepausedforuser/__init__.py#L28-L31).

2021-02-24 14:52 UTC, cp2004 commented
I would go the opposite way, and say that it would be quite helpful to know what has 'un paused' the printer from a log - it would not log that frequently at all, since the first time the printer is paused it just starts again. It would be interesting to know if starting a thread has more overhead - I suspect it does, but there is zero evidence there. Maybe I'll test it...

2021-02-24 14:54 UTC, FormerLurker commented
@jneilliii, that code only gets hit when [these conditions are true](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/a8348a5b55e0045301ca6ca7ae703b994a6dc18e/octoprint_ignorepausedforuser/__init__.py#L18-L19).  In which case the printer is paused anyway, no?

Honestly I was considering suggesting that 'enabled' is checked before the string comparison, but I'm not sure if the dict lookup is faster or slower than the string compare.  I suspect the lookup is faster, but maybe not since there is some overhead.

2021-02-24 15:14 UTC, cp2004 commented
Some comparisons here (since this got me interested) - Each test done 100000 times:

* Logging a single line `A message` to a file took 0.000067secs
* Creating a thread to do the logging in took 0.00030secs
* Simple Dict lookup - just a simple dict, rather than the overhead of OctoPrint's settings (which is a thing) - 0.00000024secs
* OctoPrint settings lookup - single key from the config - 0.000017secs
* Checking for the string in the line - 0.00000042secs

In order, from smallest to largest:
* Simple dict
* Checking string
* OctoPrint settings
* Logging
* Thread start

I don't think it is worth any difference

2021-02-24 15:25 UTC, jneilliii commented
> that code only gets hit when these conditions are true. In which case the printer is paused anyway, no?

yeah, that's why I thought it might not be such an issue.

Interesting results @cp2004 so in reality, logging a line is quicker than creating a thread. But if you follow the logic in this plugin you are logging 3 lines, and opening and writing to a json file if you follow the command from [here](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/blob/a8348a5b55e0045301ca6ca7ae703b994a6dc18e/octoprint_ignorepausedforuser/__init__.py#L31)

2021-02-24 15:32 UTC, FormerLurker commented
> Logging a single line A message to a file took 0.000067secs

If the file is already open, writing should be extremely quick, to a point.  The data is buffered, and written in the background.  Now if you overrun the buffer.....

2021-02-24 15:36 UTC, FormerLurker commented
> But if you follow the logic in this plugin you are logging 3 lines, and opening and writing to a json file if you follow the command from here

Yes, that is highly inefficient.  It is basically loading the entire file into memory, adding a record, then writing the entire file back.  Here is where we need an embedded database of some sort.

One could do something like CSV, but then 'updates' won't be efficient.  At least inserts would be constant time.

At least the history size is small (defaults to 10), so it won't be reading too much.  If it were unbounded, however....

2021-02-24 15:40 UTC, cp2004 commented
I would still vote for this to be listed, there's no 'set things on fire' potential that I can see - with a look to the future improvements.

2021-02-24 15:46 UTC, DavideM84 commented
All clear.
I will work on the reports tonight.

Thanks to all

2021-02-24 17:02 UTC, jneilliii commented
I agree @cp2004 no real concern to not merge, just as long as @DavideM84 is aware of the potential of issues.

2021-02-24 18:12 UTC, FormerLurker approved these changes
Going to approve this, but it sounds like there could be more code coming.  I may change the status depending on what I see.

2021-02-25 17:42 UTC, DavideM84 commented
Pushed code of v1.2.7 (not relased yet)

2021-02-25 18:26 UTC, jneilliii commented
@DavideM84 can you merge in my PR here, or could you make those changes to your submission, now that the date is wrong again.

https://github.com/DavideM84/plugins.octoprint.org/pull/1

2021-02-25 20:56 UTC, DavideM84 commented
@jneilliii fixed the date
Sorry but i didn't understand what else I have to do :D 
(What is missing for publishing in the repository ?)

2021-02-25 21:00 UTC, jneilliii requested changes
Just take out the email part here from the authors list and I can merge right away.

2021-02-25 21:00 UTC, jneilliii commented on _plugins/ignorepausedforuser.md
> +- Davide Mencarelli <d.mencarelli@outlook.com>
I think you should take the email address part out of this line @DavideM84

2021-02-25 21:20 UTC, DavideM84 commented on _plugins/ignorepausedforuser.md
> +- Davide Mencarelli <d.mencarelli@outlook.com>
Done (I hope :D)

2021-02-25 21:42 UTC, FormerLurker commented
FYI, I looked at the recent commits, and everything looks good.

2021-02-26 00:06 UTC, jneilliii approved these changes

2021-02-26 00:06 UTC, merged

2021-02-26 00:34 UTC, FormerLurker commented
Hooray!  I will give this a go.

2021-02-26 07:04 UTC, DavideM84 commented
Thanks to all