Added plugin print_eta
OctoPrint/plugins.octoprint.org pull request #870
Opened 2021-05-03 15:38 UTC by lewisbennett

2021-05-03 15:59 UTC, jneilliii requested changes
How is this different from [Display ETA'(https://plugins.octoprint.org/plugins/display_eta/) plugin which you apparently used as a starting point, since it's showing up in your update hook [here](https://github.com/lewisbennett/OctoPrint-Print-ETA/blob/410e5ffb8d2cc0e2e8adb5c419beaade86158b67/octoprint_print_eta/__init__.py#L64)? That needs to be `print_eta` instead of `display_eta` BTW. Also, see the failed actions above, looks like you need to fix your screenshot URL, should only be the URL.

2021-05-03 15:59 UTC, jneilliii commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
should only be the url to the image, no comments...

2021-05-03 16:13 UTC, lewisbennett commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
Hi, yes, Display ETA was used as a starting point. I and some friends have been using that plugin for a while but were experiencing issues with it, and I've been wanting to look into OctoPrint plugin development for a while, so saw it as an opportunity to learn.

Print ETA, currently, does the same job however, I have fixed the issues (mainly unreliability of ETA readings showing within OctoPrint) and feel like I've improved the settings too.

Thanks for pointing out the issues, have fixed and committed.

2021-05-03 16:16 UTC, cp2004 commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
Was there a reason you chose not to collaborate with the original author of DisplayETA to get these issues fixed and submit a Pull Request?

2021-05-03 16:22 UTC, lewisbennett commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
Not really. As I said, I wanted to look into learning about building OctoPrint plugins, so this just seemed like a good place to start.

2021-05-03 16:23 UTC, jneilliii commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
I agree, collaborating with the original plugin would have been a better approach here IMO. We are trying to limit the number of duplicated plugins on the repo, especially after the plague of filament sensor plugins.

2021-05-03 16:24 UTC, jneilliii commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
That being said, we are not trying to discourage anyone from learning plugin development and contributing to the community. If the other plugin author is not open to collaboration then of course we would accept this PR, and may anyway as it does have additional functionality (navbar) that the original plugin does not.

2021-05-03 16:28 UTC, lewisbennett commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
Alright, fair enough.

I've learnt something either way regardless if it gets published or not, so I'm happy. I may reach out to the Display ETA author like you suggested.

If nothing else, I guess it was worth a shot 😄 Thanks guys.

2021-05-03 16:30 UTC, lewisbennett commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
I'll still be using this version personally, so will likely end up adding and changing things further down the line.

I may revisit trying to publish it in the future depending on a) the outcome of reaching out to the author of Display ETA or b) adding enough additional functionality that differentiates the plugins further.

2021-05-03 16:32 UTC, jneilliii commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
I'm pretty sure that plugin was adopted by @AlexVerrico and he'll more than likely be open to collaboration.

2021-05-03 16:48 UTC, jneilliii commented
Ok, checks are passing now, github actions are happy. I was curious though, is it required that your plugin react to ever event that OctoPrint fires? It seems that's what your on_event override method is doing.

@lewisbennett if you are unable to get any response from @AlexVerrico please reply back here. I will leave this PR open in the interim, and may request @foosel to chime in on adoption of this plugin.

2021-05-03 17:01 UTC, lewisbennett commented
Not necessary, I don't think. Complete oversight actually. I did originally have it only reacting to `PrintStarted` and `PrintResumed` (I think those are right), but needed it to be more reactive, so disabled the filter. I will review the OctoPrint docs and try to filter it down some more. The plugin doesn't actually notify OctoPrint or the printer unless the string is different to the one calculated previously, but I guess querying the actual event will allow me to prevent unnecessary ETA calculations too.

Thanks again.

2021-05-03 22:09 UTC, AlexVerrico commented on _plugins/print_eta.md
> +- url: url of a screenshot, /assets/img/plugins/print_eta/screenshot.png
G'Day all. 
I'm defintely interested in collaborating, feel free to open a PR or issue over on my plugin repo if you want to discuss futher. 
Cheers, Alex.

2021-10-31 20:56 UTC, bell47 approved these changes

2021-10-31 21:02 UTC, bell47 requested changes
Kalau bisa ada perubahan lagi

2021-10-31 21:04 UTC, bell47 approved these changes

2021-11-01 10:42 UTC, foosel commented
@bell47 don't abuse the review function.

2022-01-22 18:46 UTC, closed without merging