added plugin mqtt_for_psucontrol
OctoPrint/plugins.octoprint.org pull request #880
Opened 2021-05-12 15:06 UTC by oerkel47

2021-05-12 16:00 UTC, cp2004 requested changes

2021-05-12 16:00 UTC, cp2004 commented on mqtt_for_psucontrol.md
> +featuredimage: https://github.com/oerkel47/OctoPrint-MQTT-for-PSUcontrol/blob/main/screenshot_settings.PNG
Screenshots/Featured images should be stored in the plugin repository, under /assets/img/plugins/... etc, not served from a 3rd party

2021-05-12 16:34 UTC, oerkel47 commented on mqtt_for_psucontrol.md
> +featuredimage: https://github.com/oerkel47/OctoPrint-MQTT-for-PSUcontrol/blob/main/screenshot_settings.PNG
Sorry, thought github was okay. Should be fixed!

2021-05-12 17:40 UTC, jneilliii commented
Because of it's tight integration with PSU Control, I think @kantlivelong would be the best to review/approve this one.

2021-05-12 18:05 UTC, kantlivelong approved these changes

2021-05-12 18:07 UTC, merged

2021-05-12 18:10 UTC, oerkel47 commented
Yay, my first plugin! Thanks everyone.

2021-05-12 19:15 UTC, kantlivelong commented
@oerkel47 looks like we missed one issue but I just fixed it. The md file was in the root directory instead of /_plugins/

Fixed via 39e5c8cba89331e830f86802dcea25fdf6f3cbed

2021-05-13 08:13 UTC, oerkel47 commented
Thanks..!

Just checked out the plugin page and noticed the featured image is not showing up anywhere. Is the feature broken or did I misunderstand it? Anyway..I would like to add this "missing" image to the picture settings. Can I just create another pull request for an update? This time in the correct folder..I swear ;D

2021-05-13 09:50 UTC, cp2004 commented
The featured image is used for things like the feed in OctoPrint itself and social media stuff, eg. https://mobile.twitter.com/OctoPrint3D/status/1392562165366788098

You can create as many PRs as you like, to update the plugin page when necessary.

2021-05-13 10:15 UTC, oerkel47 commented
Cool, thanks for the twitter link! That clears it up.