Added plugin ArducamCameraControl
OctoPrint/plugins.octoprint.org pull request #896
Opened 2021-06-08 09:08 UTC by ArduCAM

2021-06-08 13:53 UTC, jneilliii commented
So this plugin is a duplicate of ArducamFocus plugin with support for PTZ? Wouldn't it be better to contribute to the ArducamFocus plugin to add this support rather than having a duplicate plugin? I'm pretty sure @moof-src would be open to collaboration.

2021-06-08 15:35 UTC, moof-src commented
Arducam sent me camera samples and a link to the new plugin.  I would prefer they took over development.  In the meantime, I plan on adding their support for the PTZ to my plugin in the near future.

2021-06-08 15:47 UTC, jneilliii commented
Ok, thanks @moof-src for verifying. Only one problem I see with the current plugin @ArduCAM. The latest release version doesn't match the current version specified in setup.py, which will lead to update loops where it will keep trying to update to version 0.2 because what it thinks is installed is 0.1. Please update setup.py plugin_version and re-release 0.2 and we should be good to adopt this plugin.

2021-06-08 16:06 UTC, cp2004 requested changes

2021-06-08 16:06 UTC, cp2004 commented on _plugins/ArducamCameraControl.md
> +  - 1.2.0
The plugin makes use of `octoprint.access.Permissons`, which is good, but this is only available since OctoPrint 1.4.0, so this compatibility needs to be 1.4.0 at least.

2021-06-11 03:42 UTC, AllaboutJay commented
Hello,

Thanks for contacting Arducam.

Thank you very much for your suggestion, the matching release version is still under test, we will release it the first time after the test is complete.


If you have any questions, kindly contact us.
Thanks!

2021-06-18 15:20 UTC, jneilliii approved these changes

2021-06-18 15:25 UTC, merged