Adding Chituboard plugin to repo
OctoPrint/plugins.octoprint.org pull request #927
Opened 2021-08-17 02:44 UTC by rudetrooper

Added basic support for chituboard based printers(Elegoo Mars, Anycubic Photon, Phrozen, etc.) to octoprint.

2021-08-18 01:36 UTC, kantlivelong requested changes
1. You will need to publish your release/version @ https://github.com/rudetrooper/Octoprint-Chituboard/releases. I do see a pre-release right now.

2. It's not explicitly required but worth adjusting to lowercase [here](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/setup.py#L7) and [here](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/octoprint_chituboard/__init__.py#L497)

3. It would be better if [these options](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/octoprint_chituboard/__init__.py#L54-L64) were changed as part of a first run wizard [prompting|explaining to] the user about the changes prior to making them. This A. Informs the user of what settings the plugin requires so there's less chance of the user changing them unknowingly. B. Is cleaner

4. [Nitpick](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/octoprint_chituboard/__init__.py#L161-L174) - A lot of these settings don't appear to be used by the plugin itself. Old code? Not required to remove just thought I'd point it out.

5. I noticed that the identifier is `chituboard` but the js, css, less, templates are prefixed `sla_plugin`. These should be adjusted accordingly. See https://docs.octoprint.org/en/master/plugins/mixins.html#templateplugin

6. Tagging on to point 2, you could also include your shell script instructions during the Wizard as well. It will likely reduce some ticket traffic / uninstalls.

2021-08-18 01:42 UTC, kantlivelong commented
Nice work on the plugin, just a few things noted above. There's a lot going on so I cannot say if everything is 100% best practice but given the very specific use case and first real effort to make SLA printers work (that I know of) I think any necessary hacks are OK.

2021-08-18 23:10 UTC, rudetrooper commented on _plugins/Chituboard.md
> +date: 2021-07-16
I fixed the PR date, and added an acknowledgements sections since I used info from other repos to figure out the file structure and layer encryption.

2021-08-20 18:27 UTC, cp2004 commented
Preview URL (manually updated, experimental) https://cp2004-plugins-octoprint-org-git-pr-927-cp2004.vercel.app/

2021-08-21 22:50 UTC, rudetrooper commented
>     1. You will need to publish your release/version @ https://github.com/rudetrooper/Octoprint-Chituboard/releases. I do see a pre-release right now.
> 
>     2. It's not explicitly required but worth adjusting to lowercase [here](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/setup.py#L7) and [here](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/octoprint_chituboard/__init__.py#L497)
> 
>     3. It would be better if [these options](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/octoprint_chituboard/__init__.py#L54-L64) were changed as part of a first run wizard [prompting|explaining to] the user about the changes prior to making them. This A. Informs the user of what settings the plugin requires so there's less chance of the user changing them unknowingly. B. Is cleaner
> 
>     4. [Nitpick](https://github.com/rudetrooper/Octoprint-Chituboard/blob/dc16addfa212fd8fe48da2fec5af7c4c4737f8e1/octoprint_chituboard/__init__.py#L161-L174) - A lot of these settings don't appear to be used by the plugin itself. Old code? Not required to remove just thought I'd point it out.
> 
>     5. I noticed that the identifier is `chituboard` but the js, css, less, templates are prefixed `sla_plugin`. These should be adjusted accordingly. See https://docs.octoprint.org/en/master/plugins/mixins.html#templateplugin
> 
>     6. Tagging on to point 3, you could also include your shell script instructions during the Wizard as well. It will likely reduce some ticket traffic / uninstalls.

I finished adding the changes you requested.

2021-08-22 19:58 UTC, merged