Added BLOCKS Plugin
OctoPrint/plugins.octoprint.org pull request #929
Opened 2021-08-19 16:26 UTC by HugoCLSC

2021-08-19 19:12 UTC, jneilliii requested changes
There is quite a few things that need to be corrected in this PR. Have yet to review your plugin directly, but will do so and comment here if I see anything wrong.

2021-08-19 19:12 UTC, jneilliii commented on _plugins/BLOCKS.md
> +- (take a look at the existing plugins for what makes sense here)
remove this

2021-08-19 19:12 UTC, jneilliii commented on _plugins/BLOCKS.md
> +- url: /assets/img/plugins/ScreenShot#1.PNG
all these image URLs are incorrect, need to be `/assets/img/plugins/BLOCKS/...` paths are case sensitive.

2021-08-19 19:12 UTC, jneilliii commented on _plugins/BLOCKS.md
> +featuredimage: /assets/img/plugins/Blocks_Logo.png
same as above, but also missing the image as part of the PR.

2021-08-20 09:02 UTC, HugoCLSC commented on _plugins/BLOCKS.md
> +- url: /assets/img/plugins/ScreenShot#1.PNG
Fixed

2021-08-20 09:02 UTC, HugoCLSC commented on _plugins/BLOCKS.md
> +featuredimage: /assets/img/plugins/Blocks_Logo.png
And also fixed

2021-08-20 17:56 UTC, jneilliii commented on _plugins/BLOCKS.md
> +- url: /assets/img/plugins/ScreenShot#1.PNG
the URLs appear to still be incorrect for all the images.

2021-08-20 17:56 UTC, jneilliii commented on _plugins/BLOCKS.md
> +featuredimage: /assets/img/plugins/Blocks_Logo.png
Still don't see the image `Blocks_Logo.png` included with this PR.

2021-08-20 18:32 UTC, cp2004 commented
Preview URL (manually updated by me) https://cp2004-plugins-octoprint-org-git-pr-929-cp2004.vercel.app/

2021-08-20 20:12 UTC, HugoCLSC commented
You are completely right. I'm going to correct that asp.
Appreciate all the help

2021-08-20 20:52 UTC, cp2004 commented
I've updated the preview but it still doesn't seem to be showing the images right. It is manually updated by syncing to my own git repo, and I probably won't do it again this evening.

You can setup a local preview of the site using jekyll, follow step 4 here https://plugins.octoprint.org/help/registering/ - doing it on Linux is much easier than windows.

2021-08-20 21:00 UTC, cp2004 commented
It's likely the `#` in the URLs, don't think you can have that character.

2021-08-20 22:29 UTC, HugoCLSC commented
Sorry for all the trouble. I'll get to it when I get a chance.
Yea I was trying the Jekyll, but I'm on windows and it always bugs :/

2021-08-23 18:50 UTC, cp2004 requested changes
Just a review on the content of the page, I will leave plugin review alone and just commenting on the formatting.

Updated the preview, at least the images are showing right - my two suggestions are just to polish it off.

2021-08-23 18:50 UTC, cp2004 commented on _plugins/BLOCKS.md
> +###Acknowledgments
```suggestion
### Acknowledgments
```
Spotted this issue in the preview, Markdown wants a space

2021-08-23 18:50 UTC, cp2004 commented on _plugins/BLOCKS.md
> +*https://github.com/LazeMSS/OctoPrint-UICustomizer/
```suggestion
* https://github.com/LazeMSS/OctoPrint-UICustomizer/
```
Same as above. Need a space for formatting as a list (see preview)

2021-08-23 19:14 UTC, HugoCLSC commented on _plugins/BLOCKS.md
> +*https://github.com/LazeMSS/OctoPrint-UICustomizer/
Alright, just changed it

2021-08-23 19:30 UTC, cp2004 approved these changes
Alright, looks good from page content perspective - plugin review still to come.

2021-08-23 19:47 UTC, HugoCLSC commented
Great! Looking forward to it.

2021-08-23 21:27 UTC, jneilliii commented
I did take an initial look at your plugin and there is a concern on the effect of loading in bootstrap 5 from a CDN. Not only will that not work if the device is not connected to the internet (some people run OP isolated from the internet and access is only local) but may cause some havoc with the underlying bundled bootstrap. 

I'll try to get to a deeper review of the plugin this week just to see if there is anything else that stands out, but that was one that jumped out very quickly.

2021-08-24 10:02 UTC, HugoCLSC commented
You think i can correct that by downloading the source files of Bootstrap v5 and then just store them in my assets folder?

2021-08-31 01:18 UTC, jneilliii commented
Messing with the UI is fine, but not at the expense of messing up other plugins or core libraries. If you want to completely replace the UI that is also possible utilizing the UIPlugin mixin, which would also require handling the websocket connection for data and remove the ability to have plugin integration unless you also incorporate that functionality. Your method of replacing components is totally acceptable, and is how I do the PlotlyTempGraph replacing the built-in temperature tab. 

If your plugin requires the use of the newer bootstrap is it just css styling classes that aren't part of the bundled bootstrap? If so, maybe just incorporating the missing parts would suffice.

2021-08-31 10:38 UTC, HugoCLSC commented
Yes that does seem to be a way to fix the bootstrap problem, i'll give that a try and just add what i need from Bv5. 
For now the UIPlugin is in a shelve for me, might look into that in the near future.

2021-10-31 21:11 UTC, bell47 reviewed
Tidak buruk untuk plugin yang lebih baik

2021-12-17 14:35 UTC, jneilliii requested changes
So it seems there is one small python version mismatch noted which needs to be resolved. It also appears as if you are now bundling the bootstrap 5 library. I still think that could have some adverse effects to other plugins, but I assume the point of your plugin is that it's only yours that will be running?

2021-12-17 14:35 UTC, jneilliii commented on _plugins/BLOCKS.md
> +  python: ">=2.7,<4"
Python compatibility does not match plugin's definition. This should be `">=3.3, <4"` here and in init.py or you need to remove the python_requires from [here](https://github.com/HugoCLSC/OctoPrint-BLOCKS/blob/a36374821b27e8523ec754a7f96fc1cf7c1ffdfa/setup.py#L62).

2021-12-17 14:42 UTC, HugoCLSC commented on _plugins/BLOCKS.md
> +  python: ">=2.7,<4"
Yes the idea is to run the plugin stand alone, and continue to work on it in case there is need for new features. 
Alright just changed the python version on the .md file and on init.py.

2021-12-17 20:55 UTC, jneilliii commented
One last thing @HugoCLSC. After installing this plugin to test and verify I noticed that you are info logging on every network fetch and wifi status check. This can lead to flooding the octoprint.log, and I highly recommend switching these to `self._logger.debug` instead of `self._logger.info` to prevent log bloat. You can always change your log level for the plugin in the logging section and then get those messages when needed.

2021-12-19 14:57 UTC, HugoCLSC commented
I see what you mean, i'll apply those changes asap.

2021-12-23 11:32 UTC, HugoCLSC commented
Alright i've changed the logging levels as recommended.

2021-12-24 18:49 UTC, jneilliii approved these changes

2021-12-24 18:50 UTC, merged