Added plugin fractalbridge
OctoPrint/plugins.octoprint.org pull request #942
Opened 2021-09-15 15:42 UTC by Popeyef5

2021-09-15 19:15 UTC, jneilliii requested changes
one small extension issue commented below, and we strongly recommend having a [software update hook](https://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#octoprint-plugin-softwareupdate-check-config) so that when you release new versions all users that have it installed get update notices when you publish new releases on GitHub.

2021-09-15 19:15 UTC, jneilliii commented on _plugins/fractalbridge.md
> +featuredimage: /assets/img/plugins/fractalbridge/fractal-home.jpg
incorrect URL for image, should be .png?

2021-09-16 02:37 UTC, Popeyef5 commented on _plugins/fractalbridge.md
> +featuredimage: /assets/img/plugins/fractalbridge/fractal-home.jpg
Good catch!

2021-09-16 02:45 UTC, jneilliii commented
I think you need to make a small tweak to your software update hook implementation. Replace the line [here](https://github.com/FractalManufacturing/OctoPrint-FractalBridge/blob/master/octoprint_fractalbridge/__init__.py#L207) with the following.

```
def __plugin_load__():
    global __plugin_implementation__
    __plugin_implementation__ = FractalBridgePlugin()

    global __plugin_hooks__
    __plugin_hooks__ = {
        "octoprint.plugin.softwareupdate.check_config": __plugin_implementation__.get_update_information,
    }
```

2021-09-16 02:55 UTC, Popeyef5 commented
Thanks! Done

2021-09-16 04:07 UTC, jneilliii approved these changes
Looks good. Would love to see delta printer support.

2021-09-16 04:07 UTC, merged

2021-09-16 12:43 UTC, Popeyef5 commented
Thanks! We're launching publicly soon. In principle, it's printer agnostic (i.e. if there's a model you don't see as an option, you can just create it yourself and it will work just fine). We will definitely add Delta printer models as a default option though. We're adding a ton of features, and discussing others here: https://discord.gg/gHjjAqkVsZ

2021-09-16 13:01 UTC, jneilliii commented
You may want to give more details to your readme on github, and possibly explain more/ link to fractal site here. 

![Uploading Screenshot_20210916-085931_Discord.jpg…]()

2021-09-16 13:16 UTC, Popeyef5 commented
Yes, sorry. The initial intent was to make the plugin available for the people beta testing the platform (so that they didn't have to install via a github URL). I didn't know people paid so much attention to plugin releases. I'll be sure to tidy things up in the plugin repo and in the description of the plugin.

2021-09-16 14:01 UTC, cp2004 commented
Please send in a new PR ASAP to edit the plugin's page on the repository, with at the very least a link to where people can find out more about the service. Or an explanation that the service is not live yet. Something so we don't have to answer endless questions.