Google Drive Files
OctoPrint/plugins.octoprint.org pull request #991
Opened 2022-01-22 07:30 UTC by jneilliii

register plugin Google Drive Files

2022-01-22 07:35 UTC, jneilliii commented
come on bot, I didn't touch that file...

2022-01-22 20:03 UTC, kantlivelong requested changes
Hmm you're repo def hes some other commits in it or something? Rebase and force push maybe?

Other than that looks like just the tags need adjusting.

2022-01-22 20:03 UTC, kantlivelong commented on _plugins/googledrivefiles.md
> +tags:
These might not be the best terms for this plugin :smile:

2022-01-22 22:06 UTC, jneilliii commented
Yeah, I was fixing stuff that foosel appears to have been fixing upstream around the same time. Should be cleaned up now.

2022-01-23 00:45 UTC, kantlivelong approved these changes

2022-01-23 00:45 UTC, merged